# Generated by Django 2.1.1 on 2019-03-12 08:06

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choices',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Questions',
        ),
    ]
