# Generated by Django 2.1.1 on 2019-03-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190319_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('players', models.CharField(max_length=200)),
                ('dice', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('port', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
