# Generated by Django 2.1.7 on 2019-03-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190325_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='username',
        ),
    ]
